/// <reference path="../Scene.SceneObjectBase/index.d.ts" />


/**
[{"kind":"capability","capability":"pointCloudVisualization","orCapability":""}]
*/


/**
The 'PointCloud' class describes a point cloud generated by the World Tracking algorithm.
*/
declare interface PointCloud extends SceneObjectBase {

}
